//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HlyssUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HlyssUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;hss&gt;
        ///  &lt;!-- Filled button --&gt;
        ///  &lt;style name=&quot;filled_button_default&quot; state=&quot;default&quot;&gt;
        ///    &lt;primary-color&gt;accent&lt;/primary-color&gt;
        ///    &lt;border-thickness&gt;0&lt;/border-thickness&gt;
        ///    &lt;text-color&gt;#FFFFFF&lt;/text-color&gt;
        ///  &lt;/style&gt;
        ///
        ///  &lt;style name=&quot;filled_button_default&quot; state=&quot;hovered&quot;&gt;
        ///    &lt;primary-color&gt;accent -20&lt;/primary-color&gt;
        ///  &lt;/style&gt;
        ///
        ///  &lt;style name=&quot;filled_button_default&quot; state=&quot;pressed&quot;&gt;
        ///    &lt;primary-color&gt;accent -40&lt;/primary-color&gt;
        ///  &lt;/style&gt;
        ///
        ///  &lt;style name=&quot;filled_button_default&quot; state=&quot;disab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultStyle {
            get {
                return ResourceManager.GetString("DefaultStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;themes&gt;
        ///  &lt;theme name=&quot;light&quot; dark=&quot;false&quot;&gt;
        ///    &lt;text&gt;302b29&lt;/text&gt;
        ///    &lt;primary&gt;FAFAFA&lt;/primary&gt;
        ///    &lt;secondary&gt;d7d7d7&lt;/secondary&gt;
        ///    &lt;accent&gt;0071c5&lt;/accent&gt;
        ///    &lt;success&gt;00c230&lt;/success&gt;
        ///    &lt;error&gt;d60007&lt;/error&gt;
        ///    &lt;warning&gt;fad000&lt;/warning&gt;
        ///    &lt;information&gt;0080db&lt;/information&gt;
        ///  &lt;/theme&gt;
        ///  &lt;theme name=&quot;dark&quot; dark=&quot;true&quot;&gt;
        ///    &lt;text&gt;FFFFFF&lt;/text&gt;
        ///    &lt;primary&gt;121212&lt;/primary&gt;
        ///    &lt;secondary&gt;2D2D2D&lt;/secondary&gt;
        ///    &lt;accent&gt;3366cc&lt;/accent&gt;
        ///    &lt;success&gt;00c230&lt;/success&gt;
        ///    &lt;error&gt;d60007&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultTheme {
            get {
                return ResourceManager.GetString("DefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Empty_Image {
            get {
                object obj = ResourceManager.GetObject("Empty_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Line_Awesome {
            get {
                object obj = ResourceManager.GetObject("Line_Awesome", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Montserrat_Bold {
            get {
                object obj = ResourceManager.GetObject("Montserrat_Bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Montserrat_Medium {
            get {
                object obj = ResourceManager.GetObject("Montserrat_Medium", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Montserrat_Regular {
            get {
                object obj = ResourceManager.GetObject("Montserrat_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Montserrat_SemiBold {
            get {
                object obj = ResourceManager.GetObject("Montserrat_SemiBold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Progress_Ring {
            get {
                object obj = ResourceManager.GetObject("Progress_Ring", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
